import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs"; 
import path from "path"; 

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const outDir = "dist"; 

if (!fs.existsSync(outDir)){
    fs.mkdirSync(outDir);
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: path.join(outDir, "main.js"),
	minify: prod,
});

function copyStaticFiles() {
    console.log("Copying manifest.json to dist...");
    fs.copyFileSync("manifest.json", path.join(outDir, "manifest.json"));
    if (fs.existsSync("styles.css")) fs.copyFileSync("styles.css", path.join(outDir, "styles.css"));
}

if (prod) {
	await context.rebuild();
    copyStaticFiles(); 
	process.exit(0);
} else {
	await context.watch();
    copyStaticFiles();
}